tavros_internalApi_slope_all:
    pattern: /all
    defaults: { _controller: TavrosInternalApiBundle:Slope:all}

tavros_internalApi_slope_allName:
    pattern: /allName
    defaults: { _controller: TavrosInternalApiBundle:Slope:allName}
    