tavros_internal_api_prueba:
    pattern:  /prueba
    defaults: { _controller: TavrosInternalApiBundle:User:prueba }

tavros_help_user:
    resource: "@TavrosHelpUserBundle/Resources/config/routing.yml"
    prefix:   /user
    
#tavros_internal_api_register:
#    pattern:  /register
#    defaults: { _controller: TavrosInternalApiBundle:User:register }
