tavros_internal_api_prueba:
    pattern:  /prueba
    defaults: { _controller: TavrosInternalApiBundle:User:prueba }
    methods:   [POST]
    
tavros_internal_api_register:
    pattern:  /register
    defaults: { _controller: TavrosInternalApiBundle:User:register }
