tavros_internalApi_user:
    resource: "@TavrosInternalApiBundle/Resources/config/routing-user.yml"
    prefix:   /user

tavros_internalApi_slope:
    resource: "@TavrosInternalApiBundle/Resources/config/routing-slope.yml"
    prefix: /slope
    
#tavros_internal_api_register:
#    pattern:  /register
#    defaults: { _controller: TavrosInternalApiBundle:User:register }
