tavros_help_user_register:
    pattern:  /register
    defaults: { _controller: TavrosHelpUserBundle:Registration:register }
    
tavros_help_user_login:
    pattern:  /login
    defaults: { _controller: TavrosHelpUserBundle:Security:login }