tavros_administrator_home:
    pattern:  /
    defaults: { _controller: TavrosWebBundle:Administrator:index }

_admin_manager:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /manager
    
_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /manager
    