tavros_internalApi_alert_send:
    pattern:  /send
    defaults: { _controller: TavrosInternalApiBundle:Alert:send }

tavros_internalApi_alert_all:
    pattern:  /all
    defaults: { _controller: TavrosInternalApiBundle:Alert:all }

tavros_internalApi_alert_allUnread:
    pattern:  /allUnread
    defaults: { _controller: TavrosInternalApiBundle:Alert:allUnread }

tavros_internalApi_alert_read:
    pattern:  /read/{id}
    defaults: { _controller: TavrosInternalApiBundle:Alert:read }

tavros_internalApi_alert_read:
    pattern:  /read/all
    defaults: { _controller: TavrosInternalApiBundle:Alert:readAll }

