tavros_internalApi_skier_setPosition:
    pattern:  /setPosition
    defaults: { _controller: TavrosInternalApiBundle:Skier:setPosition }

tavros_internalApi_skier_getPosition:
    pattern: /getPosition
    defaults: { _controller: TavrosInternalApiBundle:Skier:getPosition }

tavros_internalApi_skier_getAll:
    pattern: /getAll
    defaults: { _controller: TavrosInternalApiBundle:Skier:getAll }
    
tavros_internalApi_skier_setGCMRegistrationCode:
    pattern: /setGCMRegistrationCode
    defaults: { _controller: TavrosInternalApiBundle:Skier:setGCMRegistrationCode }

tavros_internalApi_skier_offSkiMode:
    pattern: /offSkiMode
    defaults: { _controller: TavrosInternalApiBundle:Skier:offSkiMode }
