parameters:
#    tavros_internal_api.example.class: Tavros\InternalApiBundle\Example

services:
#    tavros_internal_api.example:
#        class: %tavros_internal_api.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
