Tavros\DomainBundle\Entity\Alert:
    type: entity
    repositoryClass: Tavros\DomainBundle\Repositories\AlertRepository
    table: alert
    indexes:
        FK_alert_message_idx:
            columns:
                - aler_message_id
    id:
        alerId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: aler_id
            generator:
                strategy: IDENTITY
    fields:
        alerDate:
            type: datetime
            nullable: false
            comment: ''
            column: aler_date
        alerXPosition:
            type: float
            nullable: false
            precision: 10
            scale: 0
            comment: ''
            column: aler_x_position
        alerYPosition:
            type: float
            nullable: false
            precision: 10
            scale: 0
            comment: ''
            column: aler_y_position
        alerRead:
            type: integer
            nullable: false
            column: aler_read
    manyToOne:
        alerUser:
            targetEntity: Users
            cascade: {}
            mappedBy: null
            inversedBy: null
            joinColumns:
                aler_user_id:
                    rederencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
