Tavros\DomainBundle\Entity\GeneralInformationDTO:
    type: entity
    table: general_information
    id:
        geinId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: gein_id
            generator:
                strategy: IDENTITY
    fields:
        geinCenterName:
            type: string
            nullable: true
            length: 50
            fixed: false
            comment: ''
            column: gein_center_name
        geinAmenities:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ''
            column: gein_amenities
        geinMaximumHeight:
            type: float
            nullable: true
            precision: 10
            scale: 0
            comment: ''
            column: gein_maximum_height
        geinMinimumHeight:
            type: float
            nullable: true
            precision: 10
            scale: 0
            comment: ''
            column: gein_minimum_height
        geinSeasonSince:
            type: string
            nullable: true
            length: 10
            fixed: false
            comment: ''
            column: gein_season_since
        geinSeasonTill:
            type: string
            nullable: true
            length: 10
            fixed: false
            comment: ''
            column: gein_season_till
        geinLocation:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ''
            column: gein_location
        geinDetails:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ''
            column: gein_details
        geinX:
            type: float
            nullable: false
            precision: 10
            scale: 0
            comment: ''
            column: gein_x
        geinY:
            type: float
            nullable: false
            precision: 10
            scale: 0
            comment: ''
            column: gein_y
    oneToMany:
      Schedules:
        targetEntity: HourDay
        mappedBy: hodaGeneralInformation
    lifecycleCallbacks: {  }
