Tavros\DomainBundle\Entity\Message:
    type: entity
    table: message
    indexes:
        FK_message_users_idx:
            columns:
                - mess_user_id
    id:
        messId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: mess_id
            generator:
                strategy: IDENTITY
    fields:
        messCreateddate:
            type: datetime
            nullable: false
            comment: ''
            column: mess_createdDate
    manyToOne:
        messUser:
            targetEntity: Users
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                mess_user_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
