Tavros\DomainBundle\Entity\Token:
    type: entity
    table: token
    indexes:
        fk_user_id_idx:
            columns:
                - token_user_id
    uniqueConstraints:
        token_UNIQUE:
            columns:
                - token
    id:
        tokenId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: token_id
            generator:
                strategy: IDENTITY
    fields:
        token:
            type: string
            nullable: true
            length: 45
            fixed: false
            comment: ''
    manyToOne:
        tokenUser:
            targetEntity: Users
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                token_user_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
