Tavros\DomainBundle\Entity\UserCoordinate:
    type: entity
    table: user_coordinate
    indexes:
        FK_user_coordinate_user_idx:
            columns:
                - usco_user_id
        FK_user_coordinate_coordinate_idx:
            columns:
                - usco_coordinate_id
    id:
        uscoId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: usco_id
            generator:
                strategy: IDENTITY
    fields:
        uscoUpdateDate:
            type: datetime
            nullable: true
            comment: ''
            column: usco_update_date
    manyToOne:
        uscoCoordinate:
            targetEntity: Coordinate
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                usco_coordinate_id:
                    referencedColumnName: coor_id
            orphanRemoval: false
        uscoUser:
            targetEntity: Users
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                usco_user_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
