parameters:
#    tavros_domain.example.class: Tavros\DomainBundle\Example

services:
#    tavros_domain.example:
#        class: %tavros_domain.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
