Tavros\DomainBundle\Entity\Coordinate:
    type: entity
    table: coordinate
    id:
        coorId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: coor_id
            generator:
                strategy: IDENTITY
    fields:
        coorCreatedDate:
            type: datetime
            nullable: false
            comment: ''
            column: coor_created_date
        coorX:
            type: float
            nullable: false
            precision: 10
            scale: 0
            comment: ''
            column: coor_x
        coorY:
            type: float
            nullable: false
            precision: 10
            scale: 0
            comment: ''
            column: coor_y
    lifecycleCallbacks: {  }
