Tavros\DomainBundle\Entity\MessageType:
    type: entity
    table: message_type
    id:
        metyId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: mety_id
            generator:
                strategy: IDENTITY
    fields:
        metyDescription:
            type: string
            nullable: false
            length: 45
            fixed: false
            comment: ''
            column: mety_description
    lifecycleCallbacks: {  }
