Tavros\DomainBundle\Entity\SlopeDificulty:
    type: entity
    table: slope_dificulty
    indexes:
        FK_slope_dificulty_color_idx:
            columns:
                - sldi_color_id
    id:
        sldiId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: sldi_id
            generator:
                strategy: IDENTITY
    fields:
        sldiDescription:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
            column: sldi_description
    manyToOne:
        sldiColor:
            targetEntity: Color
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                sldi_color_id:
                    referencedColumnName: colo_id
            orphanRemoval: false
    lifecycleCallbacks: {  }
