Tavros\DomainBundle\Entity\Users:
    type: entity
    table: users
    uniqueConstraints:
        UNIQ_1483A5E992FC23A8:
            columns:
                - username_canonical
        UNIQ_1483A5E9A0D96FBF:
            columns:
                - email_canonical
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY