Tavros\DomainBundle\Entity\UserCoordinate:
    type: entity
    repositoryClass: Tavros\DomainBundle\Repositories\UserCoordinateRepository
    table: user_coordinate
    indexes:
        FK_user_coordinate_user_idx:
            columns:
                - usco_user_id
        FK_user_coordinate_coordinate_idx:
            columns:
                - usco_coordinate_id
    id:
        uscoId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: usco_id
            generator:
                strategy: IDENTITY
    fields:
        uscoUpdateDate:
            type: datetime
            nullable: true
            comment: ''
            column: usco_update_date
        uscoSkiMode:
            type: integer
            nullable: false
            column: usco_ski_mode
    manyToOne:
        uscoCoordinate:
            targetEntity: Coordinate
            cascade: ["persist", "refresh"]
            mappedBy: null
            inversedBy: null
            joinColumns:
                usco_coordinate_id:
                    referencedColumnName: coor_id
            orphanRemoval: false
        uscoUser:
            targetEntity: Users
            cascade: ["persist"]
            mappedBy: null
            inversedBy: null
            joinColumns:
                usco_user_id:
                    referencedColumnName: id
            orphanRemoval: false
        uscoAlert:
            targetEntity: Alert
            cascade: ["persist"]
            mappedBy: null
            inversedBy: usco_alert_id
            joinColumns:
                usco_alert_id:
                    referencedColumnName: aler_id
            orphanRemoval: false
    lifecycleCallbacks: {  }
