parameters:
#    tavros_help_user.example.class: Tavros\HelpUserBundle\Example

services:
#    tavros_help_user.example:
#        class: %tavros_help_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
